### PR TITLE
Updated Impact numbers, replaced DALYs with lives

### PR DESCRIPTION
**Pull request by gruban**

### CODE REVIEW

**Comment by colophonemes** [comment]
Thanks @gruban, this looks great. The only additional thing would be to add sources for these numbers to the `README.md`. Would you be able to add another header under 'Other Data Sources + Import Instructions' in the README, with a list of the sources for each of the new numbers (ideally with original + archive.org links?).

**Comment by colophonemes** [comment]
(If you have these in another format and it'd be easier for you to just give me that, I can add these myself if that'd work better for you)

**Comment by gruban** [comment]
@colophonemes Ok, I can do that, I've just asked Luke for the links

**Comment by gruban** [comment]
@colophonemes I updated the Readme, it seems Google Spreadsheets are not in archive.org

**Pull request merged**
